CREATE TABLE IF NOT EXISTS institution
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100)                            NOT NULL,
    code       VARCHAR(50)                             NOT NULL,
    alias      VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_institution PRIMARY KEY (id),
    CONSTRAINT uk_institution_code UNIQUE (code)
);
