CREATE TABLE IF NOT EXISTS member
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    username          VARCHAR(50)                             NOT NULL,
    password          VARCHAR(255)                            NOT NULL,
    is_admin          BOOLEAN                                 NOT NULL,
    full_name         VARCHAR(255)                            NOT NULL,
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    email             VARCHAR(255)                            NOT NULL,
    birth_date        date,
    phone_number      VARCHAR(255),
    is_email_verified BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_member PRIMARY KEY (id)
);

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_constraint
                       WHERE conname = 'uk_email') THEN
            ALTER TABLE member
                ADD CONSTRAINT uk_email UNIQUE (email);
        END IF;
    END
$$;

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_constraint
                       WHERE conname = 'uk_username') THEN
            ALTER TABLE member
                ADD CONSTRAINT uk_username UNIQUE (username);
        END IF;
    END
$$;