CREATE TABLE IF NOT EXISTS refresh_token
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    member_id            BIGINT                                  NOT NULL,
    jti                  UUID                                    NOT NULL,
    token_hash           VARCHAR(64)                             NOT NULL,
    expires_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    revoked_at           TIMESTAMP WITHOUT TIME ZONE,
    revoked_reason       VARCHAR(20),
    replaced_by_token_id BIGINT,
    user_agent           TEXT,
    ip_address           VARCHAR(45),
    created_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (id)
);

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_constraint
                       WHERE conname = 'uk_refresh_token_hash') THEN
            ALTER TABLE refresh_token
                ADD CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash);
        END IF;
    END
$$;

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_constraint
                       WHERE conname = 'uk_refresh_token_jti') THEN
            ALTER TABLE refresh_token
                ADD CONSTRAINT uk_refresh_token_jti UNIQUE (jti);
        END IF;
    END
$$;

CREATE INDEX IF NOT EXISTS ix_refresh_token_expires_at
    ON refresh_token (expires_at);

CREATE INDEX IF NOT EXISTS ix_refresh_token_member_active
    ON refresh_token (member_id, revoked_at, expires_at);

CREATE INDEX IF NOT EXISTS ix_refresh_token_member_id
    ON refresh_token (member_id);

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_constraint
                       WHERE conname = 'fk_refresh_token_member') THEN
            ALTER TABLE refresh_token
                ADD CONSTRAINT fk_refresh_token_member FOREIGN KEY (member_id) REFERENCES member (id);
        END IF;
    END
$$;

DO
$$
    BEGIN
        IF NOT EXISTS (SELECT 1
                       FROM pg_constraint
                       WHERE conname = 'fk_refresh_token_replaced_by_token') THEN
            ALTER TABLE refresh_token
                ADD CONSTRAINT fk_refresh_token_replaced_by_token FOREIGN KEY (replaced_by_token_id) REFERENCES refresh_token (id);
        END IF;
    END
$$;