CREATE TABLE IF NOT EXISTS exam_level
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level INTEGER                                 NOT NULL,
    price INTEGER                                 NOT NULL,
    CONSTRAINT pk_exam_level PRIMARY KEY (id),
    CONSTRAINT uk_exam_level_level UNIQUE (level)
);
