CREATE TABLE IF NOT EXISTS rating_tier
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_level_id BIGINT                                  NOT NULL,
    tier          INTEGER                                 NOT NULL,
    level         VARCHAR(50)                             NOT NULL,
    min_score     INTEGER                                 NOT NULL,
    CONSTRAINT pk_rating_tier PRIMARY KEY (id),
    CONSTRAINT fk_rating_tier_exam_level FOREIGN KEY (exam_level_id) REFERENCES exam_level (id)
);

CREATE INDEX IF NOT EXISTS ix_rating_tier_exam_level_id
    ON rating_tier (exam_level_id);
