CREATE TABLE IF NOT EXISTS exam
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    level_id               BIGINT                                  NOT NULL,
    institution_id         BIGINT,
    iteration_number       INTEGER                                 NOT NULL,
    name                   VARCHAR(255)                            NOT NULL,
    registration_starts_at TIMESTAMP WITH TIME ZONE,
    registration_ends_at   TIMESTAMP WITH TIME ZONE,
    starts_at              TIMESTAMP WITH TIME ZONE,
    ends_at                TIMESTAMP WITH TIME ZONE,
    result_available_at    TIMESTAMP WITH TIME ZONE,
    created_at             TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at             TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_exam PRIMARY KEY (id),
    CONSTRAINT uk_exam_level_institution_iteration
        UNIQUE NULLS NOT DISTINCT (level_id, institution_id, iteration_number),
    CONSTRAINT FK_EXAM_EXAM_LEVEL FOREIGN KEY (level_id) REFERENCES exam_level (id),
    CONSTRAINT FK_EXAM_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institution (id)
);
CREATE INDEX IF NOT EXISTS ix_exam_institution_id
    ON exam (institution_id);