CREATE TABLE IF NOT EXISTS question_info
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_level_id   BIGINT                                  NOT NULL,
    number          INTEGER                                 NOT NULL,
    assessment_goal VARCHAR(255)                            NOT NULL,
    curriculum_code VARCHAR(255)                            NOT NULL,
    question_type   VARCHAR(100)                            NOT NULL,
    content_type    VARCHAR(100)                            NOT NULL,
    content_title   VARCHAR(255)                            NOT NULL,
    difficulty      VARCHAR(100)                            NOT NULL,
    writing_style   VARCHAR(100)                            NOT NULL,
    assessment_time INTEGER                                 NOT NULL,
    character_count INTEGER                                 NOT NULL,
    default_score   INTEGER                                 NOT NULL,
    CONSTRAINT pk_question_info PRIMARY KEY (id),
    CONSTRAINT uk_question_info_exam_level_number UNIQUE (exam_level_id, number),
    CONSTRAINT fk_question_info_exam_level FOREIGN KEY (exam_level_id) REFERENCES exam_level (id)
);

CREATE INDEX IF NOT EXISTS ix_question_info_exam_level_id
    ON question_info (exam_level_id);
