CREATE TABLE IF NOT EXISTS question_set
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_level_id BIGINT                                  NOT NULL,
    name          VARCHAR(255)                            NOT NULL,
    description   TEXT,
    difficulty    VARCHAR(100)                            NOT NULL,
    set_type      VARCHAR(30)                             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_question_set PRIMARY KEY (id),
    CONSTRAINT fk_question_set_exam_level FOREIGN KEY (exam_level_id) REFERENCES exam_level (id)
);

CREATE INDEX IF NOT EXISTS ix_question_set_exam_level_id
    ON question_set (exam_level_id);
