CREATE TABLE IF NOT EXISTS rubric
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code        VARCHAR(100)                            NOT NULL,
    description TEXT,
    sort_order  INTEGER                                 NOT NULL,
    CONSTRAINT pk_rubric PRIMARY KEY (id)
);
