CREATE TABLE IF NOT EXISTS exam_group
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id        UUID                                    NOT NULL,
    institution_id   BIGINT,
    name             VARCHAR(255)                            NOT NULL,
    iteration_number INTEGER                                 NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_exam_group PRIMARY KEY (id),
    CONSTRAINT uk_exam_group_public_id UNIQUE (public_id),
    CONSTRAINT fk_exam_group_institution FOREIGN KEY (institution_id) REFERENCES institution (id)
);

CREATE INDEX IF NOT EXISTS ix_exam_group_institution_id
    ON exam_group (institution_id);
