CREATE TABLE IF NOT EXISTS exam_session
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id             UUID                                    NOT NULL,
    member_id             BIGINT                                  NOT NULL,
    exam_id               BIGINT,
    question_set_id       BIGINT,
    examinee_country_id   BIGINT                                  NOT NULL,
    rating_tier_id        BIGINT,
    applicant_is_examinee BOOLEAN                                 NOT NULL,
    examinee_name         VARCHAR(255)                            NOT NULL,
    examinee_first_name   VARCHAR(255),
    examinee_last_name    VARCHAR(255),
    examinee_birthdate    date,
    status                VARCHAR(30)                             NOT NULL,
    registered_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    canceled_at           TIMESTAMP WITH TIME ZONE,
    started_at            TIMESTAMP WITH TIME ZONE,
    submitted_at          TIMESTAMP WITH TIME ZONE,
    graded_at             TIMESTAMP WITH TIME ZONE,
    total_score           INTEGER,
    passed                BOOLEAN                                 NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_exam_session PRIMARY KEY (id),
    CONSTRAINT uk_exam_session_public_id UNIQUE (public_id),
    CONSTRAINT uk_exam_session_exam_member UNIQUE (exam_id, member_id),
    CONSTRAINT ck_exam_session_source CHECK ((exam_id IS NOT NULL) <> (question_set_id IS NOT NULL)),
    CONSTRAINT fk_exam_session_member FOREIGN KEY (member_id) REFERENCES member (id),
    CONSTRAINT fk_exam_session_exam FOREIGN KEY (exam_id) REFERENCES exam (id),
    CONSTRAINT fk_exam_session_question_set FOREIGN KEY (question_set_id) REFERENCES question_set (id),
    CONSTRAINT fk_exam_session_examinee_country FOREIGN KEY (examinee_country_id) REFERENCES country (id),
    CONSTRAINT fk_exam_session_rating_tier FOREIGN KEY (rating_tier_id) REFERENCES rating_tier (id)
);

CREATE INDEX IF NOT EXISTS ix_exam_session_member_id
    ON exam_session (member_id);

CREATE INDEX IF NOT EXISTS ix_exam_session_question_set_id
    ON exam_session (question_set_id);

CREATE INDEX IF NOT EXISTS ix_exam_session_rating_tier_id
    ON exam_session (rating_tier_id);

CREATE INDEX IF NOT EXISTS ix_exam_session_status
    ON exam_session (status);
