CREATE TABLE IF NOT EXISTS question
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_set_id  BIGINT                                  NOT NULL,
    question_info_id BIGINT                                  NOT NULL,
    instruction      TEXT,
    content_text     TEXT,
    prompt           TEXT,
    model_answer     TEXT,
    created_at       TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_question PRIMARY KEY (id),
    CONSTRAINT uk_question_set_info UNIQUE (question_set_id, question_info_id),
    CONSTRAINT fk_question_question_set FOREIGN KEY (question_set_id) REFERENCES question_set (id),
    CONSTRAINT fk_question_question_info FOREIGN KEY (question_info_id) REFERENCES question_info (id)
);

CREATE INDEX IF NOT EXISTS ix_question_question_set_id
    ON question (question_set_id);

CREATE INDEX IF NOT EXISTS ix_question_question_info_id
    ON question (question_info_id);
