CREATE TABLE IF NOT EXISTS criterion
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    question_info_id BIGINT                                  NOT NULL,
    rubric_id        BIGINT                                  NOT NULL,
    score_value      INTEGER                                 NOT NULL,
    descriptor       TEXT                                    NOT NULL,
    CONSTRAINT pk_criterion PRIMARY KEY (id),
    CONSTRAINT uk_criterion_question_info_rubric_score UNIQUE (question_info_id, rubric_id, score_value),
    CONSTRAINT fk_criterion_question_info FOREIGN KEY (question_info_id) REFERENCES question_info (id),
    CONSTRAINT fk_criterion_rubric FOREIGN KEY (rubric_id) REFERENCES rubric (id)
);

CREATE INDEX IF NOT EXISTS ix_criterion_question_info_id
    ON criterion (question_info_id);

CREATE INDEX IF NOT EXISTS ix_criterion_rubric_id
    ON criterion (rubric_id);
