CREATE TABLE IF NOT EXISTS payment
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    exam_session_id    BIGINT                                  NOT NULL,
    portone_payment_id VARCHAR(255)                            NOT NULL,
    amount             BIGINT                                  NOT NULL,
    refund_amount      BIGINT                                  NOT NULL,
    method             VARCHAR(50)                             NOT NULL,
    status             VARCHAR(50)                             NOT NULL,
    paid_at            TIMESTAMP WITH TIME ZONE,
    canceled_at        TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_payment PRIMARY KEY (id),
    CONSTRAINT uk_payment_exam_session UNIQUE (exam_session_id),
    CONSTRAINT fk_payment_exam_session FOREIGN KEY (exam_session_id) REFERENCES exam_session (id)
);
