CREATE TABLE IF NOT EXISTS aes_task
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id       UUID                                    NOT NULL,
    exam_session_id BIGINT                                  NOT NULL,
    status          VARCHAR(50)                             NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE                NOT NULL,
    updated_at      TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_aes_task PRIMARY KEY (id),
    CONSTRAINT uk_aes_task_exam_session UNIQUE (exam_session_id),
    CONSTRAINT fk_aes_task_exam_session FOREIGN KEY (exam_session_id) REFERENCES exam_session (id)
);
