CREATE TABLE IF NOT EXISTS score
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    submitted_answer_id BIGINT                                  NOT NULL,
    rubric_id           BIGINT                                  NOT NULL,
    awarded_score       INTEGER                                 NOT NULL,
    feedback            TEXT,
    graded_at           TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_score PRIMARY KEY (id),
    CONSTRAINT uk_score_answer_rubric UNIQUE (submitted_answer_id, rubric_id),
    CONSTRAINT fk_score_submitted_answer FOREIGN KEY (submitted_answer_id) REFERENCES submitted_answer (id),
    CONSTRAINT fk_score_rubric FOREIGN KEY (rubric_id) REFERENCES rubric (id)
);

CREATE INDEX IF NOT EXISTS ix_score_submitted_answer_id
    ON score (submitted_answer_id);

CREATE INDEX IF NOT EXISTS ix_score_rubric_id
    ON score (rubric_id);
