INSERT INTO country (name,
                     code,
                     code3,
                     flag_emoji,
                     is_active)
VALUES ('Afghanistan', 'AF', 'AFG', '🇦🇫', TRUE),
       ('Albania', 'AL', 'ALB', '🇦🇱', TRUE),
       ('Algeria', 'DZ', 'DZA', '🇩🇿', TRUE),
       ('American Samoa', 'AS', 'ASM', '🇦🇸', TRUE),
       ('Andorra', 'AD', 'AND', '🇦🇩', TRUE),
       ('Angola', 'AO', 'AGO', '🇦🇴', TRUE),
       ('Anguilla', 'AI', 'AIA', '🇦🇮', TRUE),
       ('Antarctica', 'AQ', 'ATA', '🇦🇶', TRUE),
       ('Antigua and Barbuda', 'AG', 'ATG', '🇦🇬', TRUE),
       ('Argentina', 'AR', 'ARG', '🇦🇷', TRUE),
       ('Armenia', 'AM', 'ARM', '🇦🇲', TRUE),
       ('Aruba', 'AW', 'ABW', '🇦🇼', TRUE),
       ('Australia', 'AU', 'AUS', '🇦🇺', TRUE),
       ('Austria', 'AT', 'AUT', '🇦🇹', TRUE),
       ('Azerbaijan', 'AZ', 'AZE', '🇦🇿', TRUE),
       ('Bahamas', 'BS', 'BHS', '🇧🇸', TRUE),
       ('Bahrain', 'BH', 'BHR', '🇧🇭', TRUE),
       ('Bangladesh', 'BD', 'BGD', '🇧🇩', TRUE),
       ('Barbados', 'BB', 'BRB', '🇧🇧', TRUE),
       ('Belarus', 'BY', 'BLR', '🇧🇾', TRUE),
       ('Belgium', 'BE', 'BEL', '🇧🇪', TRUE),
       ('Belize', 'BZ', 'BLZ', '🇧🇿', TRUE),
       ('Benin', 'BJ', 'BEN', '🇧🇯', TRUE),
       ('Bermuda', 'BM', 'BMU', '🇧🇲', TRUE),
       ('Bhutan', 'BT', 'BTN', '🇧🇹', TRUE),
       ('Bolivia', 'BO', 'BOL', '🇧🇴', TRUE),
       ('Bosnia and Herzegovina', 'BA', 'BIH', '🇧🇦', TRUE),
       ('Botswana', 'BW', 'BWA', '🇧🇼', TRUE),
       ('Bouvet Island', 'BV', 'BVT', '🇧🇻', TRUE),
       ('Brazil', 'BR', 'BRA', '🇧🇷', TRUE),
       ('British Indian Ocean Territory', 'IO', 'IOT', '🇮🇴', TRUE),
       ('British Virgin Islands', 'VG', 'VGB', '🇻🇬', TRUE),
       ('Brunei', 'BN', 'BRN', '🇧🇳', TRUE),
       ('Bulgaria', 'BG', 'BGR', '🇧🇬', TRUE),
       ('Burkina Faso', 'BF', 'BFA', '🇧🇫', TRUE),
       ('Burundi', 'BI', 'BDI', '🇧🇮', TRUE),
       ('Cambodia', 'KH', 'KHM', '🇰🇭', TRUE),
       ('Cameroon', 'CM', 'CMR', '🇨🇲', TRUE),
       ('Canada', 'CA', 'CAN', '🇨🇦', TRUE),
       ('Cape Verde', 'CV', 'CPV', '🇨🇻', TRUE),
       ('Caribbean Netherlands', 'BQ', 'BES', '🇧🇶', TRUE),
       ('Cayman Islands', 'KY', 'CYM', '🇰🇾', TRUE),
       ('Central African Republic', 'CF', 'CAF', '🇨🇫', TRUE),
       ('Chad', 'TD', 'TCD', '🇹🇩', TRUE),
       ('Chile', 'CL', 'CHL', '🇨🇱', TRUE),
       ('China', 'CN', 'CHN', '🇨🇳', TRUE),
       ('Christmas Island', 'CX', 'CXR', '🇨🇽', TRUE),
       ('Cocos (Keeling) Islands', 'CC', 'CCK', '🇨🇨', TRUE),
       ('Colombia', 'CO', 'COL', '🇨🇴', TRUE),
       ('Comoros', 'KM', 'COM', '🇰🇲', TRUE),
       ('Cook Islands', 'CK', 'COK', '🇨🇰', TRUE),
       ('Costa Rica', 'CR', 'CRI', '🇨🇷', TRUE),
       ('Croatia', 'HR', 'HRV', '🇭🇷', TRUE),
       ('Cuba', 'CU', 'CUB', '🇨🇺', TRUE),
       ('Curacao', 'CW', 'CUW', '🇨🇼', TRUE),
       ('Cyprus', 'CY', 'CYP', '🇨🇾', TRUE),
       ('Czechia', 'CZ', 'CZE', '🇨🇿', TRUE),
       ('Democratic Republic of the Congo', 'CD', 'COD', '🇨🇩', TRUE),
       ('Denmark', 'DK', 'DNK', '🇩🇰', TRUE),
       ('Djibouti', 'DJ', 'DJI', '🇩🇯', TRUE),
       ('Dominica', 'DM', 'DMA', '🇩🇲', TRUE),
       ('Dominican Republic', 'DO', 'DOM', '🇩🇴', TRUE),
       ('East Timor', 'TL', 'TLS', '🇹🇱', TRUE),
       ('Ecuador', 'EC', 'ECU', '🇪🇨', TRUE),
       ('Egypt', 'EG', 'EGY', '🇪🇬', TRUE),
       ('El Salvador', 'SV', 'SLV', '🇸🇻', TRUE),
       ('Equatorial Guinea', 'GQ', 'GNQ', '🇬🇶', TRUE),
       ('Eritrea', 'ER', 'ERI', '🇪🇷', TRUE),
       ('Estonia', 'EE', 'EST', '🇪🇪', TRUE),
       ('Eswatini', 'SZ', 'SWZ', '🇸🇿', TRUE),
       ('Ethiopia', 'ET', 'ETH', '🇪🇹', TRUE),
       ('Falkland Islands', 'FK', 'FLK', '🇫🇰', TRUE),
       ('Faroe Islands', 'FO', 'FRO', '🇫🇴', TRUE),
       ('Federated States of Micronesia', 'FM', 'FSM', '🇫🇲', TRUE),
       ('Fiji', 'FJ', 'FJI', '🇫🇯', TRUE),
       ('Finland', 'FI', 'FIN', '🇫🇮', TRUE),
       ('France', 'FR', 'FRA', '🇫🇷', TRUE),
       ('French Guiana', 'GF', 'GUF', '🇬🇫', TRUE),
       ('French Polynesia', 'PF', 'PYF', '🇵🇫', TRUE),
       ('French Southern and Antarctic Lands', 'TF', 'ATF', '🇹🇫', TRUE),
       ('Gabon', 'GA', 'GAB', '🇬🇦', TRUE),
       ('Gambia', 'GM', 'GMB', '🇬🇲', TRUE),
       ('Georgia', 'GE', 'GEO', '🇬🇪', TRUE),
       ('Germany', 'DE', 'DEU', '🇩🇪', TRUE),
       ('Ghana', 'GH', 'GHA', '🇬🇭', TRUE),
       ('Gibraltar', 'GI', 'GIB', '🇬🇮', TRUE),
       ('Greece', 'GR', 'GRC', '🇬🇷', TRUE),
       ('Greenland', 'GL', 'GRL', '🇬🇱', TRUE),
       ('Grenada', 'GD', 'GRD', '🇬🇩', TRUE),
       ('Guadeloupe', 'GP', 'GLP', '🇬🇵', TRUE),
       ('Guam', 'GU', 'GUM', '🇬🇺', TRUE),
       ('Guatemala', 'GT', 'GTM', '🇬🇹', TRUE),
       ('Guernsey', 'GG', 'GGY', '🇬🇬', TRUE),
       ('Guinea', 'GN', 'GIN', '🇬🇳', TRUE),
       ('Guinea-Bissau', 'GW', 'GNB', '🇬🇼', TRUE),
       ('Guyana', 'GY', 'GUY', '🇬🇾', TRUE),
       ('Haiti', 'HT', 'HTI', '🇭🇹', TRUE),
       ('Heard Island and McDonald Islands', 'HM', 'HMD', '🇭🇲', TRUE),
       ('Honduras', 'HN', 'HND', '🇭🇳', TRUE),
       ('Hong Kong', 'HK', 'HKG', '🇭🇰', TRUE),
       ('Hungary', 'HU', 'HUN', '🇭🇺', TRUE),
       ('Iceland', 'IS', 'ISL', '🇮🇸', TRUE),
       ('India', 'IN', 'IND', '🇮🇳', TRUE),
       ('Indonesia', 'ID', 'IDN', '🇮🇩', TRUE),
       ('Iran', 'IR', 'IRN', '🇮🇷', TRUE),
       ('Iraq', 'IQ', 'IRQ', '🇮🇶', TRUE),
       ('Ireland', 'IE', 'IRL', '🇮🇪', TRUE),
       ('Isle of Man', 'IM', 'IMN', '🇮🇲', TRUE),
       ('Israel', 'IL', 'ISR', '🇮🇱', TRUE),
       ('Italy', 'IT', 'ITA', '🇮🇹', TRUE),
       ('Ivory Coast', 'CI', 'CIV', '🇨🇮', TRUE),
       ('Jamaica', 'JM', 'JAM', '🇯🇲', TRUE),
       ('Japan', 'JP', 'JPN', '🇯🇵', TRUE),
       ('Jersey', 'JE', 'JEY', '🇯🇪', TRUE),
       ('Jordan', 'JO', 'JOR', '🇯🇴', TRUE),
       ('Kazakhstan', 'KZ', 'KAZ', '🇰🇿', TRUE),
       ('Kenya', 'KE', 'KEN', '🇰🇪', TRUE),
       ('Kiribati', 'KI', 'KIR', '🇰🇮', TRUE),
       ('Kosovo', 'XK', 'XKX', '🇽🇰', TRUE),
       ('Kuwait', 'KW', 'KWT', '🇰🇼', TRUE),
       ('Kyrgyzstan', 'KG', 'KGZ', '🇰🇬', TRUE),
       ('Laos', 'LA', 'LAO', '🇱🇦', TRUE),
       ('Latvia', 'LV', 'LVA', '🇱🇻', TRUE),
       ('Lebanon', 'LB', 'LBN', '🇱🇧', TRUE),
       ('Lesotho', 'LS', 'LSO', '🇱🇸', TRUE),
       ('Liberia', 'LR', 'LBR', '🇱🇷', TRUE),
       ('Libya', 'LY', 'LBY', '🇱🇾', TRUE),
       ('Liechtenstein', 'LI', 'LIE', '🇱🇮', TRUE),
       ('Lithuania', 'LT', 'LTU', '🇱🇹', TRUE),
       ('Luxembourg', 'LU', 'LUX', '🇱🇺', TRUE),
       ('Macao', 'MO', 'MAC', '🇲🇴', TRUE),
       ('Madagascar', 'MG', 'MDG', '🇲🇬', TRUE),
       ('Malawi', 'MW', 'MWI', '🇲🇼', TRUE),
       ('Malaysia', 'MY', 'MYS', '🇲🇾', TRUE),
       ('Maldives', 'MV', 'MDV', '🇲🇻', TRUE),
       ('Mali', 'ML', 'MLI', '🇲🇱', TRUE),
       ('Malta', 'MT', 'MLT', '🇲🇹', TRUE),
       ('Marshall Islands', 'MH', 'MHL', '🇲🇭', TRUE),
       ('Martinique', 'MQ', 'MTQ', '🇲🇶', TRUE),
       ('Mauritania', 'MR', 'MRT', '🇲🇷', TRUE),
       ('Mauritius', 'MU', 'MUS', '🇲🇺', TRUE),
       ('Mayotte', 'YT', 'MYT', '🇾🇹', TRUE),
       ('Mexico', 'MX', 'MEX', '🇲🇽', TRUE),
       ('Moldova', 'MD', 'MDA', '🇲🇩', TRUE),
       ('Mongolia', 'MN', 'MNG', '🇲🇳', TRUE),
       ('Montenegro', 'ME', 'MNE', '🇲🇪', TRUE),
       ('Montserrat', 'MS', 'MSR', '🇲🇸', TRUE),
       ('Morocco', 'MA', 'MAR', '🇲🇦', TRUE),
       ('Mozambique', 'MZ', 'MOZ', '🇲🇿', TRUE),
       ('Myanmar', 'MM', 'MMR', '🇲🇲', TRUE),
       ('Namibia', 'NA', 'NAM', '🇳🇦', TRUE),
       ('Nauru', 'NR', 'NRU', '🇳🇷', TRUE),
       ('Nepal', 'NP', 'NPL', '🇳🇵', TRUE),
       ('Netherlands', 'NL', 'NLD', '🇳🇱', TRUE),
       ('New Caledonia', 'NC', 'NCL', '🇳🇨', TRUE),
       ('New Zealand', 'NZ', 'NZL', '🇳🇿', TRUE),
       ('Nicaragua', 'NI', 'NIC', '🇳🇮', TRUE),
       ('Niger', 'NE', 'NER', '🇳🇪', TRUE),
       ('Nigeria', 'NG', 'NGA', '🇳🇬', TRUE),
       ('Niue', 'NU', 'NIU', '🇳🇺', TRUE),
       ('Norfolk Island', 'NF', 'NFK', '🇳🇫', TRUE),
       ('North Korea', 'KP', 'PRK', '🇰🇵', FALSE),
       ('North Macedonia', 'MK', 'MKD', '🇲🇰', TRUE),
       ('Northern Mariana Islands', 'MP', 'MNP', '🇲🇵', TRUE),
       ('Norway', 'NO', 'NOR', '🇳🇴', TRUE),
       ('Oman', 'OM', 'OMN', '🇴🇲', TRUE),
       ('Pakistan', 'PK', 'PAK', '🇵🇰', TRUE),
       ('Palau', 'PW', 'PLW', '🇵🇼', TRUE),
       ('Palestine', 'PS', 'PSE', '🇵🇸', TRUE),
       ('Panama', 'PA', 'PAN', '🇵🇦', TRUE),
       ('Papua New Guinea', 'PG', 'PNG', '🇵🇬', TRUE),
       ('Paraguay', 'PY', 'PRY', '🇵🇾', TRUE),
       ('Peru', 'PE', 'PER', '🇵🇪', TRUE),
       ('Philippines', 'PH', 'PHL', '🇵🇭', TRUE),
       ('Pitcairn Islands', 'PN', 'PCN', '🇵🇳', TRUE),
       ('Poland', 'PL', 'POL', '🇵🇱', TRUE),
       ('Portugal', 'PT', 'PRT', '🇵🇹', TRUE),
       ('Principality of Monaco', 'MC', 'MCO', '🇲🇨', TRUE),
       ('Puerto Rico', 'PR', 'PRI', '🇵🇷', TRUE),
       ('Qatar', 'QA', 'QAT', '🇶🇦', TRUE),
       ('Republic of the Congo', 'CG', 'COG', '🇨🇬', TRUE),
       ('Reunion', 'RE', 'REU', '🇷🇪', TRUE),
       ('Romania', 'RO', 'ROU', '🇷🇴', TRUE),
       ('Russia', 'RU', 'RUS', '🇷🇺', TRUE),
       ('Rwanda', 'RW', 'RWA', '🇷🇼', TRUE),
       ('Saint Barthelemy', 'BL', 'BLM', '🇧🇱', TRUE),
       ('Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '🇸🇭', TRUE),
       ('Saint Kitts and Nevis', 'KN', 'KNA', '🇰🇳', TRUE),
       ('Saint Lucia', 'LC', 'LCA', '🇱🇨', TRUE),
       ('Saint Martin', 'MF', 'MAF', '🇲🇫', TRUE),
       ('Saint Pierre and Miquelon', 'PM', 'SPM', '🇵🇲', TRUE),
       ('Saint Vincent and the Grenadines', 'VC', 'VCT', '🇻🇨', TRUE),
       ('Samoa', 'WS', 'WSM', '🇼🇸', TRUE),
       ('San Marino', 'SM', 'SMR', '🇸🇲', TRUE),
       ('Sao Tome and Principe', 'ST', 'STP', '🇸🇹', TRUE),
       ('Saudi Arabia', 'SA', 'SAU', '🇸🇦', TRUE),
       ('Senegal', 'SN', 'SEN', '🇸🇳', TRUE),
       ('Serbia', 'RS', 'SRB', '🇷🇸', TRUE),
       ('Seychelles', 'SC', 'SYC', '🇸🇨', TRUE),
       ('Sierra Leone', 'SL', 'SLE', '🇸🇱', TRUE),
       ('Singapore', 'SG', 'SGP', '🇸🇬', TRUE),
       ('Sint Maarten', 'SX', 'SXM', '🇸🇽', TRUE),
       ('Slovakia', 'SK', 'SVK', '🇸🇰', TRUE),
       ('Slovenia', 'SI', 'SVN', '🇸🇮', TRUE),
       ('Solomon Islands', 'SB', 'SLB', '🇸🇧', TRUE),
       ('Somalia', 'SO', 'SOM', '🇸🇴', TRUE),
       ('South Africa', 'ZA', 'ZAF', '🇿🇦', TRUE),
       ('South Georgia and South Sandwich Islands', 'GS', 'SGS', '🇬🇸', TRUE),
       ('South Korea', 'KR', 'KOR', '🇰🇷', FALSE),
       ('South Sudan', 'SS', 'SSD', '🇸🇸', TRUE),
       ('Spain', 'ES', 'ESP', '🇪🇸', TRUE),
       ('Sri Lanka', 'LK', 'LKA', '🇱🇰', TRUE),
       ('Sudan', 'SD', 'SDN', '🇸🇩', TRUE),
       ('Suriname', 'SR', 'SUR', '🇸🇷', TRUE),
       ('Svalbard', 'SJ', 'SJM', '🇸🇯', TRUE),
       ('Sweden', 'SE', 'SWE', '🇸🇪', TRUE),
       ('Switzerland', 'CH', 'CHE', '🇨🇭', TRUE),
       ('Syria', 'SY', 'SYR', '🇸🇾', TRUE),
       ('Taiwan', 'TW', 'TWN', '🇹🇼', TRUE),
       ('Tajikistan', 'TJ', 'TJK', '🇹🇯', TRUE),
       ('Tanzania', 'TZ', 'TZA', '🇹🇿', TRUE),
       ('Thailand', 'TH', 'THA', '🇹🇭', TRUE),
       ('Togo', 'TG', 'TGO', '🇹🇬', TRUE),
       ('Tokelau', 'TK', 'TKL', '🇹🇰', TRUE),
       ('Tonga', 'TO', 'TON', '🇹🇴', TRUE),
       ('Trinidad and Tobago', 'TT', 'TTO', '🇹🇹', TRUE),
       ('Tunisia', 'TN', 'TUN', '🇹🇳', TRUE),
       ('Turkey', 'TR', 'TUR', '🇹🇷', TRUE),
       ('Turkmenistan', 'TM', 'TKM', '🇹🇲', TRUE),
       ('Turks and Caicos Islands', 'TC', 'TCA', '🇹🇨', TRUE),
       ('Tuvalu', 'TV', 'TUV', '🇹🇻', TRUE),
       ('Uganda', 'UG', 'UGA', '🇺🇬', TRUE),
       ('Ukraine', 'UA', 'UKR', '🇺🇦', TRUE),
       ('United Arab Emirates', 'AE', 'ARE', '🇦🇪', TRUE),
       ('United Kingdom', 'GB', 'GBR', '🇬🇧', TRUE),
       ('United States Minor Outlying Islands', 'UM', 'UMI', '🇺🇲', TRUE),
       ('United States of America', 'US', 'USA', '🇺🇸', TRUE),
       ('Uruguay', 'UY', 'URY', '🇺🇾', TRUE),
       ('Uzbekistan', 'UZ', 'UZB', '🇺🇿', TRUE),
       ('Vanuatu', 'VU', 'VUT', '🇻🇺', TRUE),
       ('Vatican City', 'VA', 'VAT', '🇻🇦', TRUE),
       ('Venezuela', 'VE', 'VEN', '🇻🇪', TRUE),
       ('Vietnam', 'VN', 'VNM', '🇻🇳', TRUE),
       ('Virgin Islands', 'VI', 'VIR', '🇻🇮', TRUE),
       ('Wallis and Futuna', 'WF', 'WLF', '🇼🇫', TRUE),
       ('Western Sahara', 'EH', 'ESH', '🇪🇭', TRUE),
       ('Yemen', 'YE', 'YEM', '🇾🇪', TRUE),
       ('Zambia', 'ZM', 'ZMB', '🇿🇲', TRUE),
       ('Zimbabwe', 'ZW', 'ZWE', '🇿🇼', TRUE),
       ('Åland Islands', 'AX', 'ALA', '🇦🇽', TRUE)
ON CONFLICT (code) DO NOTHING;